const Achievement = require('../models/Achievement');
const Goal        = require('../models/Goal');

const ENCOURAGE = [
  { min: 75,  max: 79,  msg: "⚡ You're 75% there — finish strong!", badge: '🔥 On Fire' },
  { min: 80,  max: 84,  msg: "💪 Great momentum! Don't stop now!",   badge: '💪 Pushing Hard' },
  { min: 85,  max: 89,  msg: "🚀 Almost there! Keep the energy up!", badge: '🚀 Almost Done' },
  { min: 90,  max: 94,  msg: "🌟 So close! Final stretch!",          badge: '🌟 Final Stretch' },
  { min: 95,  max: 99,  msg: "🔥 Just a tiny push left — do it!",    badge: '🔥 Nearly There' },
  { min: 100, max: 100, msg: "🏆 Goal completed! Achievement unlocked!", badge: '🏆 Completed' },
];

const getEncourageMsg = (progress) =>
  ENCOURAGE.find(e => progress >= e.min && progress <= e.max) || ENCOURAGE[0];

// Auto-sync all goals ≥75% as achievements
const syncGoalAchievements = async (userId) => {
  const goals = await Goal.find({ user: userId, progress: { $gte: 75 } });
  for (const goal of goals) {
    const exists = await Achievement.findOne({ user: userId, linkedGoal: goal._id });
    const enc    = getEncourageMsg(goal.progress);
    if (!exists) {
      await Achievement.create({
        user:          userId,
        title:         goal.title,
        description:   goal.progress === 100
          ? `🏆 Goal completed! ${goal.description || ''}`
          : `${enc.msg} (${goal.progress}% done)`,
        type:          goal.goalType === 'Professional' ? 'Performance' : 'Development',
        date:          goal.actualCompletionDate || goal.updatedAt,
        linkedGoal:    goal._id,
        progress:      goal.progress,
        autoGenerated: true,
      });
    } else {
      // Update progress if changed
      if (exists.progress !== goal.progress) {
        exists.progress    = goal.progress;
        exists.description = goal.progress === 100
          ? `🏆 Goal completed! ${goal.description || ''}`
          : `${enc.msg} (${goal.progress}% done)`;
        await exists.save();
      }
    }
  }
};

// GET /api/achievements
const getAchievements = async (req, res) => {
  try {
    await syncGoalAchievements(req.user.id);
    const { type } = req.query;
    const filter   = { user: req.user.id };
    if (type && type !== 'All') filter.type = type;

    const achievements = await Achievement
      .find(filter)
      .populate('linkedGoal', 'title category priority progress status')
      .sort({ date: -1 });

    res.status(200).json({ success: true, data: achievements });
  } catch (err) {
    console.error('getAchievements error:', err);
    res.status(500).json({ success: false, message: 'Failed to fetch achievements' });
  }
};

// POST /api/achievements (manual - kept for flexibility)
const createAchievement = async (req, res) => {
  try {
    const { title, description, type, date } = req.body;
    if (!title?.trim())
      return res.status(400).json({ success: false, message: 'Title is required' });
    const ach = await Achievement.create({
      user: req.user.id, title, description, type,
      date: date || new Date(), autoGenerated: false,
    });
    res.status(201).json({ success: true, message: 'Achievement added!', data: ach });
  } catch (err) {
    res.status(500).json({ success: false, message: 'Failed to create achievement' });
  }
};

// DELETE /api/achievements/:id
const deleteAchievement = async (req, res) => {
  try {
    const ach = await Achievement.findOneAndDelete({ _id: req.params.id, user: req.user.id });
    if (!ach) return res.status(404).json({ success: false, message: 'Not found' });
    res.status(200).json({ success: true, message: 'Achievement deleted!' });
  } catch (err) {
    res.status(500).json({ success: false, message: 'Failed to delete' });
  }
};

module.exports = { getAchievements, createAchievement, deleteAchievement };