const Goal        = require('../models/Goal');
const Habit       = require('../models/Habit');
const Achievement = require('../models/Achievement');
const Post        = require('../models/Post');
const User        = require('../models/User');
const DevPlan     = require('../models/DevPlan');
const ScoreCard   = require('../models/ScoreCard');
const { Course }  = require('../models/Course');
const Notification = require('../models/Notification');

// ─── GOALS ───────────────────────────────────────────────────────────────────
const getAllGoals = async (req, res) => {
  try {
    const { userId, status } = req.query;
    const filter = {};
    if (userId) filter.user = userId;
    if (status && status !== 'All') filter.status = status;
    const goals = await Goal.find(filter).populate('user','name email').sort({ createdAt: -1 }).limit(100);
    res.status(200).json({ success: true, data: goals });
  } catch (err) { res.status(500).json({ success: false, message: 'Failed to fetch goals' }); }
};

const updateGoal = async (req, res) => {
  try {
    const goal = await Goal.findByIdAndUpdate(req.params.id, req.body, { new: true });
    if (!goal) return res.status(404).json({ success: false, message: 'Goal not found' });
    res.status(200).json({ success: true, message: 'Goal updated!', data: goal });
  } catch (err) { res.status(500).json({ success: false, message: 'Failed to update goal' }); }
};

const deleteGoal = async (req, res) => {
  try {
    await Goal.findByIdAndDelete(req.params.id);
    res.status(200).json({ success: true, message: 'Goal deleted!' });
  } catch (err) { res.status(500).json({ success: false, message: 'Failed to delete goal' }); }
};

// ─── HABITS ──────────────────────────────────────────────────────────────────
const getAllHabits = async (req, res) => {
  try {
    const { userId } = req.query;
    const filter = userId ? { user: userId } : {};
    const habits = await Habit.find(filter).populate('user','name email').sort({ createdAt: -1 }).limit(100);
    res.status(200).json({ success: true, data: habits });
  } catch (err) { res.status(500).json({ success: false, message: 'Failed to fetch habits' }); }
};

const resetHabit = async (req, res) => {
  try {
    const habit = await Habit.findById(req.params.id);
    if (!habit) return res.status(404).json({ success: false, message: 'Habit not found' });
    habit.days = Array(21).fill(false);
    await habit.save();
    res.status(200).json({ success: true, message: 'Habit reset!', data: habit });
  } catch (err) { res.status(500).json({ success: false, message: 'Failed to reset habit' }); }
};

const deleteHabit = async (req, res) => {
  try {
    await Habit.findByIdAndDelete(req.params.id);
    res.status(200).json({ success: true, message: 'Habit deleted!' });
  } catch (err) { res.status(500).json({ success: false, message: 'Failed to delete habit' }); }
};

// ─── ACHIEVEMENTS ─────────────────────────────────────────────────────────────
const addAchievement = async (req, res) => {
  try {
    const { userId, title, description, type } = req.body;
    if (!userId || !title)
      return res.status(400).json({ success: false, message: 'userId and title required' });
    const ach = await Achievement.create({ user: userId, title, description, type: type || 'Other', autoGenerated: false });
    res.status(201).json({ success: true, message: 'Achievement added!', data: ach });
  } catch (err) { res.status(500).json({ success: false, message: 'Failed to add achievement' }); }
};

const deleteAchievement = async (req, res) => {
  try {
    await Achievement.findByIdAndDelete(req.params.id);
    res.status(200).json({ success: true, message: 'Achievement deleted!' });
  } catch (err) { res.status(500).json({ success: false, message: 'Failed to delete achievement' }); }
};

// ─── COURSES ──────────────────────────────────────────────────────────────────
const getAllCourses = async (req, res) => {
  try {
    const courses = await Course.find().sort({ createdAt: -1 });
    res.status(200).json({ success: true, data: courses });
  } catch (err) { res.status(500).json({ success: false, message: 'Failed to fetch courses' }); }
};

const createCourse = async (req, res) => {
  try {
    const { title, category, duration, instructor, skillTag } = req.body;
    if (!title || !category || !duration || !instructor)
      return res.status(400).json({ success: false, message: 'All fields required' });
    const course = await Course.create({ title, category, duration, instructor, skillTag: skillTag || '' });
    res.status(201).json({ success: true, message: 'Course created!', data: course });
  } catch (err) { res.status(500).json({ success: false, message: 'Failed to create course' }); }
};

const updateCourse = async (req, res) => {
  try {
    const course = await Course.findByIdAndUpdate(req.params.id, req.body, { new: true });
    if (!course) return res.status(404).json({ success: false, message: 'Course not found' });
    res.status(200).json({ success: true, message: 'Course updated!', data: course });
  } catch (err) { res.status(500).json({ success: false, message: 'Failed to update course' }); }
};

const deleteCourse = async (req, res) => {
  try {
    await Course.findByIdAndDelete(req.params.id);
    res.status(200).json({ success: true, message: 'Course deleted!' });
  } catch (err) { res.status(500).json({ success: false, message: 'Failed to delete course' }); }
};

// ─── COMMUNITY ────────────────────────────────────────────────────────────────
const getAllPosts = async (req, res) => {
  try {
    const posts = await Post.find()
      .populate('user','name email suspended')
      .sort({ createdAt: -1 })
      .limit(100);
    res.status(200).json({ success: true, data: posts });
  } catch (err) { res.status(500).json({ success: false, message: 'Failed to fetch posts' }); }
};

const deletePost = async (req, res) => {
  try {
    await Post.findByIdAndDelete(req.params.id);
    res.status(200).json({ success: true, message: 'Post deleted!' });
  } catch (err) { res.status(500).json({ success: false, message: 'Failed to delete post' }); }
};

const deleteComment = async (req, res) => {
  try {
    const post = await Post.findById(req.params.postId);
    if (!post) return res.status(404).json({ success: false, message: 'Post not found' });
    post.comments = post.comments.filter(c => c._id.toString() !== req.params.commentId);
    await post.save();
    res.status(200).json({ success: true, message: 'Comment deleted!' });
  } catch (err) { res.status(500).json({ success: false, message: 'Failed to delete comment' }); }
};

// ─── DEV PLAN ─────────────────────────────────────────────────────────────────
const addDevPlanRec = async (req, res) => {
  try {
    const { userId, title, type, duration, priority, reason } = req.body;
    let plan = await DevPlan.findOne({ user: userId });
    if (!plan) plan = await DevPlan.create({ user: userId, recommendations: [], milestones: [] });
    plan.recommendations.push({ title, type: type || 'Custom', duration: duration || '1 hour', priority: priority || 'medium', reason: reason || '', completed: false, icon: 'FaRocket' });
    await plan.save();
    res.status(201).json({ success: true, message: 'Recommendation added!', data: plan });
  } catch (err) { res.status(500).json({ success: false, message: 'Failed to add recommendation' }); }
};

const removeDevPlanRec = async (req, res) => {
  try {
    const plan = await DevPlan.findOne({ user: req.params.userId });
    if (!plan) return res.status(404).json({ success: false, message: 'Dev plan not found' });
    plan.recommendations = plan.recommendations.filter(r => r._id.toString() !== req.params.recId);
    await plan.save();
    res.status(200).json({ success: true, message: 'Recommendation removed!', data: plan });
  } catch (err) { res.status(500).json({ success: false, message: 'Failed to remove recommendation' }); }
};

// ─── NOTIFICATIONS ────────────────────────────────────────────────────────────
const sendNotification = async (req, res) => {
  try {
    const { userId, title, message, type } = req.body;
    if (!title || !message) return res.status(400).json({ success: false, message: 'Title and message required' });

    if (userId) {
      // User-specific
      await Notification.create({ user: userId, title, message, type: type || 'info', global: false });
    } else {
      // Global — send to all users
      const users = await User.find({ role: 'user' }).select('_id');
      await Notification.insertMany(users.map(u => ({ user: u._id, title, message, type: type || 'info', global: true })));
    }

    res.status(201).json({ success: true, message: userId ? 'Notification sent to user!' : `Notification sent to all users!` });
  } catch (err) { res.status(500).json({ success: false, message: 'Failed to send notification' }); }
};

const getNotifications = async (req, res) => {
  try {
    const notifs = await Notification.find()
      .populate('user', 'name email')
      .sort({ createdAt: -1 })
      .limit(50);
    res.status(200).json({ success: true, data: notifs });
  } catch (err) { res.status(500).json({ success: false, message: 'Failed to fetch notifications' }); }
};

module.exports = {
  getAllGoals, updateGoal, deleteGoal,
  getAllHabits, resetHabit, deleteHabit,
  addAchievement, deleteAchievement,
  getAllCourses, createCourse, updateCourse, deleteCourse,
  getAllPosts, deletePost, deleteComment,
  addDevPlanRec, removeDevPlanRec,
  sendNotification, getNotifications,
};