const Goal = require("../models/Goal");
const Achievement = require("../models/Achievement");

// Helper: auto-create achievement when goal is completed
const syncAchievement = async (goal, userId) => {
  try {
    const exists = await Achievement.findOne({
      user: userId,
      linkedGoal: goal._id,
    });
    if (!exists) {
      await Achievement.create({
        user: userId,
        title: goal.title,
        description: goal.description || `Completed: ${goal.title}`,
        type: goal.goalType === "Professional" ? "Performance" : "Development",
        date: goal.actualCompletionDate || new Date(),
        linkedGoal: goal._id,
        autoGenerated: true,
      });
    }
  } catch (err) {
    console.error("syncAchievement error:", err);
  }
};

// GET /api/goals
const getGoals = async (req, res) => {
  try {
    const { status, category, goalType } = req.query;
    const filter = { user: req.user.id };
    if (status && status !== "All") filter.status = status;
    if (category && category !== "All") filter.category = category;
    if (goalType) filter.goalType = goalType;
    const goals = await Goal.find(filter).sort({ createdAt: -1 });
    res.status(200).json({ success: true, data: goals });
  } catch (error) {
    res.status(500).json({ success: false, message: "Failed to fetch goals" });
  }
};

// POST /api/goals
const createGoal = async (req, res) => {
  try {
    const {
      title,
      description,
      priority,
      tags,
      category,
      goalType,
      startDate,
      expectedEndDate,
      expectedDueDate,
      effortRequired,
      weightage,
      measurementCriteria,
      coach,
    } = req.body;

    if (!title?.trim())
      return res
        .status(400)
        .json({ success: false, message: "Title is required" });

    const goal = await Goal.create({
      user: req.user.id,
      title,
      description,
      priority,
      tags,
      category,
      goalType,
      startDate,
      expectedEndDate,
      expectedDueDate,
      effortRequired,
      weightage,
      measurementCriteria,
      coach,
    });
    res
      .status(201)
      .json({ success: true, message: "Goal created!", data: goal });
  } catch (error) {
    if (error.name === "ValidationError") {
      return res
        .status(400)
        .json({
          success: false,
          message: Object.values(error.errors)[0].message,
        });
    }
    res.status(500).json({ success: false, message: "Failed to create goal" });
  }
};

// PUT /api/goals/:id
const updateGoal = async (req, res) => {
  try {
    const goal = await Goal.findOne({ _id: req.params.id, user: req.user.id });
    if (!goal)
      return res
        .status(404)
        .json({ success: false, message: "Goal not found" });

    const allowed = [
      "title",
      "description",
      "progress",
      "priority",
      "status",
      "tags",
      "category",
      "goalType",
      "startDate",
      "expectedEndDate",
      "expectedDueDate",
      "effortRequired",
      "weightage",
      "measurementCriteria",
      "coach",
      "accomplishment",
      "actualCompletionDate",
    ];

    allowed.forEach((field) => {
      if (req.body[field] !== undefined) goal[field] = req.body[field];
    });

    // Auto-update status based on progress
    if (req.body.progress !== undefined) {
      if (req.body.progress === 100) {
        goal.status = "Completed";
        goal.actualCompletionDate = goal.actualCompletionDate || new Date();
      } else if (req.body.progress > 0) {
        goal.status = "In Progress";
      }
    }

    // If status is manually set to Completed
    if (req.body.status === "Completed") {
      goal.actualCompletionDate = goal.actualCompletionDate || new Date();
    }

    await goal.save();

    // Auto-generate achievement if goal just completed
    if (goal.status === "Completed") {
      await syncAchievement(goal, req.user.id);
    }

    res
      .status(200)
      .json({ success: true, message: "Goal updated!", data: goal });
  } catch (error) {
    res.status(500).json({ success: false, message: "Failed to update goal" });
  }
};

// DELETE /api/goals/:id
const deleteGoal = async (req, res) => {
  try {
    const goal = await Goal.findOneAndDelete({
      _id: req.params.id,
      user: req.user.id,
    });
    if (!goal)
      return res
        .status(404)
        .json({ success: false, message: "Goal not found" });

    // Also delete linked auto-generated achievement
    await Achievement.deleteOne({
      linkedGoal: req.params.id,
      autoGenerated: true,
    });

    res.status(200).json({ success: true, message: "Goal deleted!" });
  } catch (error) {
    res.status(500).json({ success: false, message: "Failed to delete goal" });
  }
};

// POST /api/goals/:id/subgoals
const addSubGoal = async (req, res) => {
  try {
    const goal = await Goal.findOne({ _id: req.params.id, user: req.user.id });
    if (!goal)
      return res
        .status(404)
        .json({ success: false, message: "Goal not found" });

    const {
      name,
      description,
      startDate,
      expectedDueDate,
      weightage,
      measurementCriteria,
      requiredEffort,
    } = req.body;
    if (!name?.trim())
      return res
        .status(400)
        .json({ success: false, message: "Sub-goal name is required" });

    goal.subGoals.push({
      name,
      description,
      startDate,
      expectedDueDate,
      weightage,
      measurementCriteria,
      requiredEffort,
    });
    await goal.save();
    res
      .status(201)
      .json({ success: true, message: "Sub-goal added!", data: goal });
  } catch (error) {
    res.status(500).json({ success: false, message: "Failed to add sub-goal" });
  }
};

// PUT /api/goals/:id/subgoals/:subId
const updateSubGoal = async (req, res) => {
  try {
    const goal = await Goal.findOne({ _id: req.params.id, user: req.user.id });
    if (!goal)
      return res
        .status(404)
        .json({ success: false, message: "Goal not found" });

    const sub = goal.subGoals.id(req.params.subId);
    if (!sub)
      return res
        .status(404)
        .json({ success: false, message: "Sub-goal not found" });

    const fields = [
      "name",
      "description",
      "startDate",
      "expectedDueDate",
      "weightage",
      "measurementCriteria",
      "requiredEffort",
      "utilizedEffort",
      "spentEffort",
      "status",
      "accomplishment",
      "actualCompletionDate",
    ];
    fields.forEach((f) => {
      if (req.body[f] !== undefined) sub[f] = req.body[f];
    });

    await goal.save();
    res
      .status(200)
      .json({ success: true, message: "Sub-goal updated!", data: goal });
  } catch (error) {
    res
      .status(500)
      .json({ success: false, message: "Failed to update sub-goal" });
  }
};

// DELETE /api/goals/:id/subgoals/:subId
const deleteSubGoal = async (req, res) => {
  try {
    const goal = await Goal.findOne({ _id: req.params.id, user: req.user.id });
    if (!goal)
      return res
        .status(404)
        .json({ success: false, message: "Goal not found" });

    goal.subGoals = goal.subGoals.filter(
      (s) => s._id.toString() !== req.params.subId,
    );
    await goal.save();
    res
      .status(200)
      .json({ success: true, message: "Sub-goal deleted!", data: goal });
  } catch (error) {
    res
      .status(500)
      .json({ success: false, message: "Failed to delete sub-goal" });
  }
};

module.exports = {
  getGoals,
  createGoal,
  updateGoal,
  deleteGoal,
  addSubGoal,
  updateSubGoal,
  deleteSubGoal,
};
