const mongoose = require("mongoose");

const achievementSchema = new mongoose.Schema(
  {
    user: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
    title: { type: String, required: true, trim: true },
    description: { type: String, default: "" },
    type: {
      type: String,
      enum: ["Performance", "Development", "Other"],
      default: "Other",
    },
    date: { type: Date, default: Date.now },
    linkedGoal: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Goal",
      default: null,
    },
    progress: { type: Number, default: 100 }, // goal progress at time of sync
    autoGenerated: { type: Boolean, default: false },
  },
  { timestamps: true },
);

module.exports = mongoose.model("Achievement", achievementSchema);
