import { useState, useEffect } from "react";
import DashboardLayout from "@/components/layout/DashboardLayout";
import { api } from "@/utils/api";
import { useNavigate } from "react-router-dom";
import toast from "react-hot-toast";
import {
  FaTrophy,
  FaFire,
  FaStar,
  FaArrowRight,
  FaMedal,
} from "react-icons/fa";

interface Achievement {
  _id: string;
  title: string;
  description: string;
  type: string;
  date: string;
  progress: number;
  autoGenerated: boolean;
  linkedGoal?: {
    title: string;
    category: string;
    priority: string;
    progress: number;
    status: string;
  };
}

const TYPES = ["All", "Performance", "Development", "Other"];

// Progress badge config
const getProgressBadge = (progress: number) => {
  if (progress === 100)
    return {
      label: "🏆 Completed",
      color: "bg-success/20 text-success border-success/40",
      ring: "ring-success",
    };
  if (progress >= 95)
    return {
      label: "🔥 Nearly There",
      color: "bg-destructive/10 text-destructive border-destructive/30",
      ring: "ring-destructive",
    };
  if (progress >= 90)
    return {
      label: "🚀 Final Stretch",
      color: "bg-secondary/20 text-secondary-foreground border-secondary/30",
      ring: "ring-secondary",
    };
  if (progress >= 80)
    return {
      label: "💪 Pushing Hard",
      color: "bg-primary/10 text-primary border-primary/30",
      ring: "ring-primary",
    };
  return {
    label: "⚡ In Progress",
    color: "bg-muted text-foreground-muted border-border",
    ring: "ring-muted",
  };
};

const getEncouragementMsg = (progress: number) => {
  if (progress === 100) return "🎉 Outstanding! You crushed this goal!";
  if (progress >= 95) return "🔥 Just a tiny push! You're basically done!";
  if (progress >= 90)
    return "🚀 So close! Don't stop now — the finish line is right there!";
  if (progress >= 85) return "🌟 Incredible progress! Keep the momentum going!";
  if (progress >= 80) return "💪 You're in the home stretch! Stay consistent!";
  if (progress >= 75)
    return "⚡ 75% done! You've built great momentum — keep it up!";
  return "Keep going!";
};

const typeColor = (t: string) =>
  t === "Performance"
    ? "bg-primary-light text-primary"
    : t === "Development"
      ? "bg-secondary/20 text-secondary-foreground"
      : "bg-muted text-foreground-muted";

export default function AchievementsPage() {
  const [achievements, setAchievements] = useState<Achievement[]>([]);
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState("All");
  const navigate = useNavigate();

  useEffect(() => {
    api
      .get("/achievements")
      .then((r) => setAchievements(r.data.data))
      .catch(() => toast.error("Failed to load achievements"))
      .finally(() => setLoading(false));
  }, []);

  const filtered =
    filter === "All"
      ? achievements
      : achievements.filter((a) => a.type === filter);

  // Split into completed (100%) and in-progress (75-99%)
  const completed = filtered.filter((a) => a.progress === 100);
  const inProgress = filtered.filter(
    (a) => a.progress >= 75 && a.progress < 100,
  );

  return (
    <DashboardLayout>
      <div className="space-y-6 animate-fade-in">
        {/* Header */}
        <div className="flex justify-between items-start">
          <div>
            <h1 className="text-2xl md:text-3xl font-bold">My Achievements</h1>
            <p className="text-foreground-muted mt-1">
              Auto-earned from your goals — starts showing at 75% progress 🎯
            </p>
          </div>
          <button
            onClick={() => navigate("/goals")}
            className="btn-secondary text-sm flex items-center gap-2 shrink-0"
          >
            Go to Goals <FaArrowRight className="w-3 h-3" />
          </button>
        </div>

        {/* Stats */}
        {achievements.length > 0 && (
          <div className="grid grid-cols-4 gap-3">
            {[
              {
                label: "Total",
                val: achievements.length,
                color: "text-primary",
                bg: "bg-primary/10",
              },
              {
                label: "Completed",
                val: achievements.filter((a) => a.progress === 100).length,
                color: "text-success",
                bg: "bg-success/10",
              },
              {
                label: "In Progress",
                val: achievements.filter((a) => a.progress < 100).length,
                color: "text-secondary",
                bg: "bg-secondary/10",
              },
              {
                label: "Performance",
                val: achievements.filter((a) => a.type === "Performance")
                  .length,
                color: "text-destructive",
                bg: "bg-destructive/10",
              },
            ].map((s, i) => (
              <div key={i} className={`${s.bg} rounded-xl p-3 text-center`}>
                <p className={`text-2xl font-bold ${s.color}`}>{s.val}</p>
                <p className="text-xs text-foreground-muted mt-0.5">
                  {s.label}
                </p>
              </div>
            ))}
          </div>
        )}

        {/* Filters */}
        <div className="flex gap-2 flex-wrap">
          {TYPES.map((t) => (
            <button
              key={t}
              onClick={() => setFilter(t)}
              className={`px-4 py-2 rounded-lg text-sm font-medium transition-all ${
                filter === t
                  ? "bg-primary text-primary-foreground"
                  : "bg-muted text-foreground-muted hover:bg-accent"
              }`}
            >
              {t}
              <span className="ml-1.5 text-xs opacity-70">
                (
                {t === "All"
                  ? achievements.length
                  : achievements.filter((a) => a.type === t).length}
                )
              </span>
            </button>
          ))}
        </div>

        {loading && (
          <div className="flex justify-center py-12">
            <div className="w-8 h-8 border-4 border-primary border-t-transparent rounded-full animate-spin" />
          </div>
        )}

        {/* Empty state */}
        {!loading && achievements.length === 0 && (
          <div className="text-center py-16">
            <FaTrophy className="text-6xl mx-auto mb-4 opacity-20" />
            <h3 className="text-lg font-semibold mb-2">No achievements yet</h3>
            <p className="text-foreground-muted text-sm mb-2">
              Push any goal past <strong>75%</strong> to earn your first
              achievement!
            </p>
            <p className="text-xs text-foreground-muted mb-6">
              Complete a goal to get 🏆 Completed badge
            </p>
            <button
              onClick={() => navigate("/goals")}
              className="btn-primary flex items-center gap-2 mx-auto"
            >
              Go to Goals <FaArrowRight className="w-3 h-3" />
            </button>
          </div>
        )}

        {/* ─── In Progress Achievements (75–99%) ─────────────────────────── */}
        {!loading && inProgress.length > 0 && (
          <div className="space-y-3">
            <h2 className="font-semibold flex items-center gap-2 text-secondary">
              <FaFire /> Keep Going — You're Almost There!
            </h2>
            {inProgress.map((a) => {
              const badge = getProgressBadge(a.progress);
              return (
                <div
                  key={a._id}
                  className={`card-elevated border-l-4 ${
                    a.progress >= 95
                      ? "border-l-destructive"
                      : a.progress >= 90
                        ? "border-l-secondary"
                        : a.progress >= 80
                          ? "border-l-primary"
                          : "border-l-success"
                  }`}
                >
                  <div className="flex items-start justify-between gap-3 mb-3">
                    <div className="flex items-center gap-3">
                      <div
                        className={`w-10 h-10 rounded-full border-2 ${badge.ring} flex items-center justify-center shrink-0`}
                      >
                        <FaMedal className="text-secondary text-lg" />
                      </div>
                      <div>
                        <h3 className="font-semibold text-sm">{a.title}</h3>
                        <p className="text-xs text-foreground-muted mt-0.5">
                          {getEncouragementMsg(a.progress)}
                        </p>
                      </div>
                    </div>
                    <div className="text-right shrink-0">
                      <p className="text-2xl font-bold text-secondary">
                        {a.progress}%
                      </p>
                      <span
                        className={`text-xs px-2 py-0.5 rounded-full border font-medium ${badge.color}`}
                      >
                        {badge.label}
                      </span>
                    </div>
                  </div>
                  {/* Progress bar */}
                  <div className="w-full bg-muted rounded-full h-2.5">
                    <div
                      className={`rounded-full h-2.5 transition-all duration-700 ${
                        a.progress >= 95
                          ? "bg-destructive"
                          : a.progress >= 90
                            ? "bg-secondary"
                            : a.progress >= 80
                              ? "bg-primary"
                              : "bg-success"
                      }`}
                      style={{ width: `${a.progress}%` }}
                    />
                  </div>
                  <div className="flex justify-between text-xs text-foreground-muted mt-1">
                    <span>{a.progress}% done</span>
                    <span className="text-destructive font-medium">
                      {100 - a.progress}% left to complete! 💪
                    </span>
                  </div>
                  {a.linkedGoal && (
                    <button
                      onClick={() => navigate("/goals")}
                      className="mt-2 text-xs text-primary hover:underline flex items-center gap-1"
                    >
                      🎯 Update this goal in Goals page →
                    </button>
                  )}
                </div>
              );
            })}
          </div>
        )}

        {/* ─── Completed Achievements (100%) ─────────────────────────────── */}
        {!loading && completed.length > 0 && (
          <div className="space-y-3">
            <h2 className="font-semibold flex items-center gap-2 text-success">
              <FaTrophy /> Completed Achievements 🏆
            </h2>
            <div className="grid md:grid-cols-2 gap-4">
              {completed.map((a) => (
                <div
                  key={a._id}
                  className="card-elevated border-l-4 border-l-success bg-success/5"
                >
                  <div className="flex items-start gap-3">
                    <div className="w-11 h-11 rounded-xl bg-success/20 flex items-center justify-center shrink-0">
                      <FaTrophy className="text-success text-lg" />
                    </div>
                    <div className="flex-1 min-w-0">
                      <h3 className="font-semibold text-sm">{a.title}</h3>
                      <p className="text-xs text-foreground-muted mt-0.5 line-clamp-2">
                        {a.description}
                      </p>
                      <div className="flex items-center gap-2 mt-2 flex-wrap">
                        <span
                          className={`text-xs px-2 py-0.5 rounded-full font-medium ${typeColor(a.type)}`}
                        >
                          {a.type}
                        </span>
                        {a.autoGenerated && (
                          <span className="text-xs bg-success/10 text-success px-2 py-0.5 rounded-full flex items-center gap-1">
                            <FaStar className="w-2.5 h-2.5" /> From Goal
                          </span>
                        )}
                        {a.linkedGoal?.category && (
                          <span className="text-xs text-foreground-muted">
                            {a.linkedGoal.category}
                          </span>
                        )}
                        <span className="text-xs text-foreground-muted ml-auto">
                          {new Date(a.date).toLocaleDateString("en-IN", {
                            day: "numeric",
                            month: "short",
                            year: "numeric",
                          })}
                        </span>
                      </div>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {!loading && achievements.length > 0 && (
          <p className="text-center text-xs text-foreground-muted py-2">
            🏆 Push any goal past 75% to see it here · Complete it to earn the
            full achievement!
          </p>
        )}
      </div>
    </DashboardLayout>
  );
}
